name: 'Kolga Setup'
description: 'This action is used to setup Kolga for Github Actions'
runs:
  using: 'composite'
  steps:
    - name: Parse Variables
      run: |
          echo "repo_name=${github_repo//['_/']/-}" >> $GITHUB_ENV
          echo "pr_id=${pull_request_id:0:3}" >> $GITHUB_ENV
          echo "github_head_ref=${github_head_ref//['_/.']/-}" >> $GITHUB_ENV
          github_ref_tmp=${github_ref##*/}
          echo "github_ref=${github_ref_tmp//['_/.']/-}" >> $GITHUB_ENV
      shell: bash
      env:
        github_head_ref: ${{ github.event.pull_request.head.ref }}
        github_ref: ${{ github.ref }}
        github_repo: ${{ github.event.repository.name }}
        pull_request_id: ${{ github.event.pull_request.id }}

    - name: Set K8S_NAMESPACE
      run: |
          namespace_prefix=${repo_name}-${github_head_ref}
          namespace="${namespace_prefix:0:59}-${pr_id}"
          namespace_lowercase=${namespace,,}
          echo "K8S_NAMESPACE=${namespace_lowercase}" >> $GITHUB_ENV
      shell: bash

    - name: Set ENVIRONMENT_SLUG
      run: |
          environment_slug=${github_head_ref:-$github_ref}
          echo "ENVIRONMENT_SLUG=${environment_slug,,}" >> $GITHUB_ENV
      shell: bash

    - name: Set PROJECT_NAME
      run: echo "PROJECT_NAME=${repo_name,,}" >> $GITHUB_ENV
      shell: bash

    - name: Set K8S_ADDITIONAL_HOSTNAMES
      run: |
        echo "K8S_ADDITIONAL_HOSTNAMES=${{ secrets.K8S_ADDITIONAL_HOSTNAMES }}" >> $GITHUB_ENV
      shell: bash
